// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering.Materials
{
    public static partial class LineVisualizerShaderKeys
    {
        public static readonly ObjectParameterKey<Buffer> LineInstanceArray = ParameterKeys.NewObject<Buffer>();
        public static readonly ValueParameterKey<float> LineThicknessScale = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<uint> OccludedStyleCheckerSize = ParameterKeys.NewValue<uint>(1);
        public static readonly ValueParameterKey<uint> PassIndex = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<Matrix> ViewProjection = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> ViewProjectionInverse = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Vector2> ViewSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector3> Eye = ParameterKeys.NewValue<Vector3>();
    }
}
